apps/backend/modules/schoolyear/actions/actions.class.php

fix duplicacion de funcion schoolyear/ManualExamination

---

apps/backend/modules/career/actions/actions.class.php
lib/model/Career.php

Se soluciona el error de memoria que producia al intentar copiar mas alla del plan de estudio, tambien se le agrego a la copia el siguiente numero de alumno en 1.

fix copia de plan de estudio

---

apps/backend/modules/tentative_repproved_student/actions/actions.class.php
lib/model/CareerStudent.php

- Se soluciona el problema de los repitientes año a año en el metodo de matriculacion automatica.
- Se agrega el metodo para borrar las previas en los alumnos que no van a trayectorias al finalizar el año.

close SchoolYear

---

apps/backend/modules/career_school_year/actions/actions.class.php
lib/form/custom/MatriculateGraduatedStudentsForm.class.php
lib/model/StudentCareerSchoolYearPeer.php

- Se agrego un try-catch para si suceden errores en el medio del intento de incripcion de alumnos no incriba a ninguno y nos informe que hubo error.
- Se corrigieron algunas consultas.

Arreglos en Pasaje de alumnos egresados (de una carrera) a otra carrera.

---

apps/backend/modules/student/config/generator.yml
apps/backend/modules/student/templates/_careers.php
apps/backend/modules/student/templates/_commisions.php
apps/backend/modules/student/templates/_health_info.php
apps/backend/modules/student/templates/_student_info.php
apps/backend/modules/student/templates/_tutors.php
flavors/agropecuaria/i18n/messages.es.xml
flavors/agropecuaria/web/css/main.css
flavors/anexa/i18n/messages.es.xml
flavors/anexa/web/css/main.css
flavors/bba/i18n/messages.es.xml
flavors/bba/web/css/main.css
flavors/cnba/i18n/messages.es.xml
flavors/cnba/web/css/main.css
flavors/demo/i18n/messages.es.xml
flavors/demo/web/css/main.css
flavors/lvm/i18n/messages.es.xml
flavors/lvm/web/css/main.css
flavors/nacional/i18n/messages.es.xml
flavors/nacional/web/css/main.css
flavors/pellegrini/i18n/messages.es.xml
flavors/pellegrini/web/css/main.css

Se eliminaron vistas rapidas innecesarias, se agrego el legajo del alumno junto al nombre y se reestructuro la vista rapida de tutores.

Modificaciones en listado de alumnos

---

apps/backend/modules/examination_repproved_subject/actions/actions.class.php
apps/backend/modules/examination_repproved_subject/templates/printStudentsSuccess.php
apps/backend/modules/manual_examination_subject/actions/actions.class.php
apps/backend/modules/manual_examination_subject/templates/printStudentsSuccess.php
apps/backend/templates/_examination_act.php
flavors/nacional/modules/examination_subject/templates/printStudentsSuccess.php
flavors/nacional/modules/manual_examination_subject/templates/printStudentsSuccess.php

Se redirige el boton "atras" al modulo del que viene el usuario.

fixed boton "atras" en manual_examination y examination_repproved

---

apps/backend/modules/examination_repproved_subject/actions/actions.class.php
apps/backend/modules/examination_repproved_subject/templates/printStudentsSuccess.php
apps/backend/modules/manual_examination_subject/actions/actions.class.php
apps/backend/modules/manual_examination_subject/templates/printStudentsSuccess.php
apps/backend/templates/_examination_act.php
config/pathway-schema.yml
flavors/nacional/modules/examination_subject/templates/printStudentsSuccess.php
flavors/nacional/modules/manual_examination_subject/templates/printStudentsSuccess.php
lib/filter/StudentCareerSubjectAllowedPathwayFormFilter.class.php
lib/filter/StudentFormFilter.class.php
lib/form/PathwayCourseSubjectStudentManyForm.class.php
lib/form/StudentCareerSubjectAllowedPathwayForm.class.php
lib/form/TentativeRepprovedStudentForm.class.php
lib/model/CareerStudent.php
lib/model/Student.php
lib/model/StudentCareerSubjectAllowedPathway.php
lib/model/StudentCareerSubjectAllowedPathwayPeer.php
lib/school_behaviour/base/BaseEvaluatorBehaviour.class.php
patch/2.22.1/student_career_subject_allowed_pathway.sql

- Se separo en dos la tabla de allowed, una para el año actual y otra para las trayectorias.
- Se agrego un control para que solo se pueda inscribir en trayectorias a materias que el alumno aun debe.
- Solo se mostraran en el listado de alumnos la etiqueta "TRAYECTORIAS" a alumnos que esten o estuvieron en trayectorias en el año lectivo actual.

Separados Allowed de Allowed_Pathway

---

apps/backend/modules/pathway/config/generator.yml
apps/backend/modules/pathway_commission/actions/actions.class.php
apps/backend/modules/pathway_commission/config/generator.yml
lib/model/Course.php

- Se pusieron condiciones para algunas acciones.

arreglos en permisos y acciones de trayectorias

---

apps/backend/modules/course_student_mark/templates/_mark.php

- Queda comentada la auditoria de la carga de calificaciones por el momento.

se elimina la auditoria de la carga de calificaciones

---

flavors/lvm/i18n/messages.es.xml
lib/filter/custom/DivisionCourseFormFilter.class.php

- elimina campo is_pathway.
- Se agregan algunas traducciones faltantes de LVM.

fixed filtro de divisiones y i18n LVM

---

apps/backend/modules/commission/actions/actions.class.php
apps/backend/modules/commission/config/generator.yml
apps/backend/modules/course_student_mark/actions/actions.class.php
apps/backend/modules/course_student_mark/templates/_component_marks_info.php
apps/backend/modules/course_student_mark/templates/_mark.php
apps/backend/modules/course_student_mark/templates/changelogMarksSuccess.php
apps/backend/modules/division_course/actions/actions.class.php
apps/backend/modules/division_course/config/generator.yml
flavors/anexa/web/css/main.css
flavors/bba/web/css/main.css
flavors/lvm/web/css/main.css
flavors/nacional/web/css/main.css

- se agrega auditoria de notas como una accion separada de la carga de notas en divisiones->materias y en comisiones.
- se habilita nuevamente la auditoria de las notas en relacion a mesas de examen (se lo deja como estaba anteriormente).

Auditoria notas

---

lib/form/custom/HeadPersonalForm.class.php
lib/form/custom/StudentOfficePersonalForm.class.php

- formularios de preceptores
- formulario de personal de oficina de alumnos

agrego la seleccion de departamento en formularios

---

apps/backend/modules/attendance_justification/actions/actions.class.php

- Se agrega un orden (por fecha) al listado de justificaciones de faltas.

Ordenamiento de justificaciones de faltas

---

apps/backend/modules/course_student_mark/templates/_component_marks_info.php
apps/backend/modules/examination_repproved_subject/actions/actions.class.php
apps/backend/modules/examination_repproved_subject/config/generator.yml
apps/backend/modules/examination_repproved_subject/templates/calificationsSuccess.php
apps/backend/modules/examination_repproved_subject/templates/changelogMarksSuccess.php
apps/backend/modules/examination_subject/actions/actions.class.php
apps/backend/modules/examination_subject/config/generator.yml
apps/backend/modules/examination_subject/templates/calificationsSuccess.php
apps/backend/modules/examination_subject/templates/changelogMarksSuccess.php
apps/backend/modules/manual_examination_subject/actions/actions.class.php
apps/backend/modules/manual_examination_subject/config/generator.yml
apps/backend/modules/manual_examination_subject/templates/calificationsSuccess.php
flavors/anexa/web/css/main.css
flavors/bba/modules/course_student_mark/templates/_component_marks_info.php
flavors/bba/web/css/main.css
flavors/lvm/web/css/main.css
flavors/nacional/web/css/main.css

- Se modifico la vista de carga de calificaciones en mesas de examen, mesas manuales y mesas de previos/libres.
- Se agrego una accion de auditoria de notas en los listados de todos los tipos de mesas.

Auditoria de notas en mesas de examen, manuales y previos/libres

---

apps/backend/modules/student/templates/_commisions.php
flavors/anexa/web/css/main.css
flavors/bba/web/css/main.css
flavors/lvm/web/css/main.css
flavors/nacional/web/css/main.css

- Se modifico la forma de mostrar las comisiones en este listado, ahora si el alumno tiene mas de 3 comisiones se ocultas y existe un link "Ver todas" para expandir.

Vista Listado de alumnos

---

flavors/bba/i18n/messages.es.xml
flavors/bba/lib/behaviour/BbaAnalyticalBehaviour.class.php
lib/model/Student.php

Pequeñas modificaciones del codigo para una mejor interpretacion.

fix Analitico bba

---

flavors/lvm/modules/report_card/templates/_course_subject_trimester.php
flavors/lvm/modules/student/templates/_current_course_subjects.php
flavors/lvm/web/css/main.css
lib/model/LetterMarkPeer.php

- Se modifico las vistas para que no promedie la nota de esta materia de 1er Año.

Nota conceptual en materia de LVM

---

apps/backend/modules/student/templates/_component_analytical_table.php
flavors/nacional/lib/behavior/NacionalAnalyticalBehaviour.class.php
flavors/nacional/lib/behavior/NacionalSchoolBehaviour.class.php
flavors/nacional/lib/behavior/NacionalSubjectStudentAnalytic.php
flavors/nacional/web/css/analytics.css
flavors/nacional/web/css/print-analytics.css
lib/school_behaviour/base/BaseAnalyticalBehaviour.class.php
lib/school_behaviour/base/BaseEvaluatorBehaviour.class.php

Modificaciones que pidieron sobre el analitico.
- Se cambio la condicion para Mesas de diciembre ahora es REGULAR al igual que si aprueba durante el año.
- Se cambio la opcion de legajo global para que en el analitico apareciera el legajo de cada alumno y no el numero de incripto en la carrera.
- Se modifico el tamaño de la columna nota en numero, para que sea siempre el mismo y no variable ( variaba cuando adeudaba alguna materia).
- Se agrando la letra de las tablas de años y calificaciones.

Analitico nacional

---

apps/backend/modules/student/actions/actions.class.php
lib/form/SchoolYearStudentForm.class.php

Modifico la opcion required en false para aquellos alumnos que se matriculan en forma manual

saco required de campo date_health_info

---

flavors/anexa/web/js-frontend/scripts.js
flavors/bba/web/js-frontend/scripts.js
flavors/demo/web/js-frontend/scripts.js
flavors/lvm/web/js-frontend/scripts.js
flavors/nacional/web/js-frontend/scripts.js

Agrego script para que funcionen los navtab de bootstrap en las calificaciones.

Frontend - Agrego script para los navtab

---

flavors/lvm/modules/student/templates/_component_analytical_table.php

Se intercambio el nombre de la columna Asignatura por Materia y viceversa en el analitico de LVM.

Correccion de columnas en analitico LVM

---

lib/model/Division.php

corrección para adminsitrar alumnos en la división
